server:
  forward-headers-strategy: native
  tomcat:
    connection-timeout: 600000  # 10분
    keep-alive-timeout: 600000  # 10분
    max-keep-alive-requests: 1000
spring:
  jpa:
    hibernate:
      ddl-auto: none # 배포 시는 none 또는 validate 추천
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false

  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 40000
      idle-timeout: 600000
      max-lifetime: 1800000

      leak-detection-threshold: 180000  # 3분으로 여유롭게

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: false
      timeout: 30000          # 연결 타임아웃 30초
      lettuce:
        pool:
          max-active: 8
          max-wait: 30s     # 풀 대기시간 30초
        shutdown-timeout: 200ms

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

        provider:
          # --- Google Provider 설정 (스프링 시큐리티에 내장되어 있어 별도 설정 불필요) ---
          # --- Kakao Provider 설정 ---
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          # --- Naver Provider 설정 ---
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

#  cloud:
#    aws:
#      credentials:
#        access-key: ${AWS_ACCESS_KEY_ID}
#        secret-key: ${AWS_SECRET_ACCESS_KEY}
#      region:
#        static: ap-northeast-2
#      s3:
#        bucket: ${AWS_S3_BUCKET_NAME}
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 10MB

# JWT 설정
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30 # Access Token 유효 기간 (분)
  refresh-token-expiration-days: 7 # Refresh Token 유효 기간 (일)

logging:
  level:
    root: DEBUG
    org.pagebyfeel: DEBUG
    org.springframework: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

gemini:
  api:
    key: ${GOOGLE_GEMINI_KEY}